MGMT-13642: bump python-libvirt library to handle build failure (#2045)
When trying to build assisted-test-infra container image, it fails for
the following error:
```
  × Running setup.py install for libvirt-python did not run
successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      running install
      running build
      running build_py
      Missing type converters:
      int *:1
      ERROR: failed virDomainFDAssociate
...
```

Apparently it was fixed by
https://gitlab.com/libvirt/libvirt-python/-/tags/v9.0.0 so this bumps
the library version.