Added deploy-target argument to deploy_nodes and install_cluster (#170)
Since it is required for creating the assisted-service client in local mode.

Traceback (most recent call last):
  File "/home/raz/go/src/assisted-test-infra/discovery-infra/utils.py", line 396, in wrapped
    return fn(*args, **kwargs)
  File "discovery-infra/delete_nodes.py", line 29, in try_to_delete_cluster
    url=utils.get_assisted_service_url_by_args(args=args, wait=False)
  File "/home/raz/go/src/assisted-test-infra/discovery-infra/utils.py", line 301, in get_assisted_service_url_by_args
    kwargs['deploy_target'] = args.deploy_target
AttributeError: 'Namespace' object has no attribute 'deploy_target'